homepage/urls.py
from django.contrib import admin
from django.urls import path, include
from joinInfo.views import apply_club_user_info_view
from activity.views import upload_activity, success_page, edit_page, edit_images, activities_page
from people.views import show_people_1, show_people_2, show_people_3
from joinResult import views
from application import views
from makers.views import show_makers
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('join/', apply_club_user_info_view, name='apply_club_user_info_view'),
    path('joinResult/', include('joinResult.urls')),

    path('', include('login.urls')),

    path('upload/', upload_activity, name='upload_activity'),
    path('success/', success_page, name='success_page'),
    path('edit/', edit_page, name='edit_page'),
    path('edit_images/<int:image_id>/', edit_images, name='edit_images'),
    path('activities/', activities_page, name='activities_page'),

    path('people_1/', show_people_1, name='show_people_1'),
    path('people_2/', show_people_2, name='show_people_2'),
    path('people_3/', show_people_3, name='show_people_3'),

    path('notice/', include('notice.urls')),  

    path('application/', include('application.urls')),

    path('makers/', show_makers, name='show_makers'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('', views.home, name='home'),
    path('h/', views.health, name='health'),
]

notice/urls.py
from django.contrib import admin
from django.urls import path, include
#for images, files
from django.conf.urls.static import static
from django.conf import settings
from notice import views

app_name = 'notice'

urlpatterns = [
    path('', views.notice_list, name='notice_list'),
    path('0/<int:notion_id>/', views.notice_detail, name='notice_detail'),#0이 왜 필요한진 몰겠어요..; 근데 자꾸 주소에 0 붙어서 걍 함
    path('create/', views.notice_create, name='notice_create'),
    path('get_notices_by_category/', views.get_notices_by_category, name='get_notices_by_category'),
    path('edit_notice/<int:notion_id>/', views.edit_notice, name='edit_notice'),
]
#for images, files/ 개발 환경에서 쓸라면 이거 추가해서 직접 서빙해줘야함.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/models.py
from django.db import models

# Create your models here.
class Notion(models.Model):
    write_time = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=20, default='general')
    notion_title = models.CharField(max_length=60)
    notion_text = models.CharField(max_length=500)
    
class NotionImage(models.Model):
   notion = models.ForeignKey(Notion, on_delete=models.CASCADE)
   image = models.ImageField(upload_to='image/',blank=True, null=True)
  

class NotionFile(models.Model):
   notion = models.ForeignKey(Notion, on_delete=models.CASCADE)
   file = models.FileField(upload_to="file/",blank=True, null=True)
'''
class NotionImage(models.Model):
    notion = models.ForeignKey(Notion, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="image")# media/image/ 아래에 저장

class NotionFile(models.Model):
    notion = models.ForeignKey(Notion, on_delete=models.CASCADE)
    file = models.FileField(upload_to="file")# media/file/ 아래에 저장
'''

notice/forms.py
from django import forms
from .models import Notion, NotionImage, NotionFile

class NotionForm(forms.ModelForm):
    class Meta:
        model = Notion
        fields = ['category', 'notion_title', 'notion_text']

class NotionImageForm(forms.ModelForm):
    class Meta:
        model = NotionImage
        fields = ['image']

class NotionFileForm(forms.ModelForm):
    class Meta:
        model = NotionFile
        fields = ['file']

notice/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Notion, NotionImage, NotionFile
from .forms import NotionForm, NotionImageForm, NotionFileForm
from django.http import JsonResponse
from django.urls import reverse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required

# create
@login_required(login_url='/login/')
def notice_create(request):
    if request.method == 'POST':
        notion_title = request.POST.get('notion_title', '')
        notion_text = request.POST.get('notion_text', '')
        selected_category = request.POST.get('selectedCategory', 'general')

        # Notion 모델에 저장
        notion = Notion.objects.create(
            notion_title=notion_title,
            notion_text=notion_text,
            category=selected_category
        )

       
        images = request.FILES.getlist('image')
        files = request.FILES.getlist('file')
        for img in images:
            NotionImage.objects.create(notion=notion, image=img)
            images = request.FILES.getlist('image')
        for file in files:
            NotionFile.objects.create(notion=notion, file=file)



        return redirect('notice:notice_list')

    return render(request, 'Notice_manager_writing.html')

def get_notices_by_category(request):
    category = request.GET.get('category') 
    notices = [] 
    if category=='정기활동' :
        notices = Notion.objects.filter(category=category).order_by('-write_time')
    elif category == '행사':
        notices = Notion.objects.filter(category=category).order_by('-write_time')
    elif category == '공모전':
        notices = Notion.objects.filter(category=category).order_by('-write_time')

     #pagination처리
    page = request.GET.get('page')
    paginator = Paginator(notices, 8)
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger: #page 선택 안 했을 때
        page = 1
        page_obj = paginator.page(page)
    except EmptyPage: #notices수 보다 더 큰 page 입력했을 때 
        page = paginator.num_pages
        page_obj = paginator.page(page)
    
    #page수 많으면 그 뒤에 넘기는 거 '>'로 보이게
    leftIndex = (int(page)-2)
    if leftIndex <1:
        leftIndex = 1
    
    rightIndex = (int(page)+2)
    if rightIndex > paginator.num_pages:
        rightIndex = paginator.num_pages
    custom_range = range(leftIndex, rightIndex+1)

    return render(request, 'Notice_main.html', {'notices': notices, 'page_obj':page_obj, 'paginator':paginator, 'custom_range':custom_range})



# read

def notice_list(request):
    notices = Notion.objects.all().order_by('-write_time')

    #pagination처리
    page = request.GET.get('page')
    paginator = Paginator(notices, 8)
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger: #page 선택 안 했을 때
        page = 1
        page_obj = paginator.page(page)
    except EmptyPage: #notices수 보다 더 큰 page 입력했을 때 
        page = paginator.num_pages
        page_obj = paginator.page(page)
    
    #page수 많으면 그 뒤에 넘기는 거 '>'로 보이게
    leftIndex = (int(page)-2)
    if leftIndex <1:
        leftIndex = 1
    
    rightIndex = (int(page)+2)
    if rightIndex > paginator.num_pages:
        rightIndex = paginator.num_pages
    custom_range = range(leftIndex, rightIndex+1)

    return render(request, 'Notice_main.html', {'notices': notices, 'page_obj':page_obj, 'paginator':paginator, 'custom_range':custom_range})



def notice_detail(request, notion_id):
    notice = get_object_or_404(Notion, pk=notion_id)
    images = NotionImage.objects.filter(notion=notice)
    files = NotionFile.objects.filter(notion=notice)
    return render(request, 'Notice_manager_record.html', {'notice': notice, 'images': images, 'files': files})

@login_required(login_url='/login/')
def edit_notice(request, notion_id):
    notice = get_object_or_404(Notion, pk=notion_id)
    images = NotionImage.objects.filter(notion=notice)
    notion=Notion.objects.get(id=notion_id)
    images.delete()

    if request.method == 'POST':
        notion.notion_title = request.POST['notion_title']
        notion.notion_text = request.POST['notion_text']
        notion.category = request.POST['selectedCategory'] 

        # Notion 모델에 저장
        notion.save()

        # NotionImage 모델에 저장
        images = request.FILES.getlist('image')
        for img in images:
            NotionImage.objects.create(notion=notion, image=img)

        return redirect(reverse('notice:notice_detail', kwargs={'notion_id': notice.id}))

    return render(request, 'notice_manager_edit.html' ,{'notice': notice, 'images': images})

notice/templates/Notice_main.html
{% extends 'basic.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/Notice_main.css'%}">
    </head>
    <body>
        <div id="realContent">

    <a href="{% url 'notice:notice_list' %}"><div id="notice" class="notice">공지사항</div></a>

    <div id="Notice_title">
        <img id="star" src="{% static 'img/people/star.svg'%}" >
        <h1 id="title">Notice</h1>
    </div>

    {% if user.is_superuser %}
    <a href="{% url 'notice:notice_create' %}"><div id="writings" class="writing">글 작성</div></a>
    {% endif %}
    <div id="realContent">
    <a href="{% url 'notice:get_notices_by_category' %}?category=정기활동">
        <input type="button" id="regularActivity" class="round-button" onclick="showContent('regularActivity')" value="정기활동">
    </a>
    <a href="{% url 'notice:get_notices_by_category' %}?category=행사">
        <input type="button" id="event" class="round-button" onclick="showContent('event')" value="행사">
    </a>
    <a href="{% url 'notice:get_notices_by_category' %}?category=공모전">
        <input type="button" id="competition" class="round-button" onclick="showContent('competition')" value="공모전">
    </a>
    
    
    <div id="allContent" class="content">
        <div class="DList">
            <table class="tbl">
                <colgroup>
                    <col width="10%" />
                    <col width="10%" />
                    <col width="80%" />
                </colgroup>
                <!-- 데이터 불러온 부분 -->
                <tbody>
                    {% for notice in page_obj %}
                    <div class="box">
                    <tr onclick=location.href="{% url 'notice:notice_detail' notion_id=notice.id %}">
                        <td class="write-time">{{ notice.write_time|date:"Y.m.d" }}</td>
                        <td><div class="category">{{ notice.category }}</div></td>
                        <td><div class="overflow">{{ notice.notion_title }}</div></td>
                    </tr>
                    </div>
                    {% endfor %}
                    </tbody>
            </table>
        </div>
        <!--
        <ul>
            {% for notice in page_obj %}
            <li>
                <div class="box">
                    <span class="write-time">{{ notice.write_time|date:"Y.m.d" }}</span>
                    <span class="category">{{ notice.category }}</span>
                    <a class="notice-title" href="{% url 'notice:notice_detail' notion_id=notice.id %}"><span class="notitle">{{ notice.notion_title }}</span></a>
                </div>
            </li>
            
            {% endfor %}
        </ul>
        -->
            <div id="page">
                {% if page_obj.has_other_pages %} <!--1페이지만 있을 땐 페이지수 안 보이게 if문 달긔-->
                    <ul style="display: flex;list-style: none;">
    
                        {% if page_obj.has_previous %}<!-- 이전으로 버튼-->
                            <li style="margin:3px"><a style="text-decoration: none; color: black;" href="?page={{page_obj.previous_page_number}}">&#10094; Prev</a></li>
                        {% endif %}
    
                        {% for page in paginator.page_range %}<!-- page숫자 구현부-->
                            {% if page == page_obj.number %} <!--현재페이지 강조, 색변화-->
                                <li style="margin:3px"><a style="text-decoration: none; color:#9EA9D7;" href="?page={{page}}">{{page}}</a></li>
                            {% else %} <!--그 외 (분기문. 야 뭔말인지 알즤)-->
                                <li style="margin:3px"><a style="text-decoration: none; color: black;" href="?page={{page}}">{{page}}</a></li>
                            {% endif %}
                        {% endfor %}
    
                        {% if page_obj.has_next %} <!--next버튼-->
                            <li style="margin:3px"><a style="text-decoration: none; color: black;" href="?page={{page_obj.next_page_number}}">&#10095; Next</a></li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div> 
    </div>
</div>
</div>
</body> 
<script src="{% static 'js/Notice_main.js' %}"></script>
{% endblock %}

notice/templates/Notice_manager_edit.html
{% extends 'basic.html' %}
{% load static %}

    {% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Notice_manager_writing.css' %}">
    <div id="realContent">
    <form action="{% url 'notice:edit_notice' notion_id=notice.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <a href="{% url 'notice:notice_list' %}"><div id="notices" class="notice"><span>공지사항</span></div></a>
        <a href="{% url 'notice:notice_create' %}"><input type="button" id="writings" class="writing" value="글 작성"></a>
        <input type="button" id="regularActivity" name="정기활동" class="round-button" onclick="updateHiddenValue(this)" value="정기활동">
        <input type="button" id="event" name="행사" class="round-button" onclick="updateHiddenValue(this)" value="행사">
        <input type="button" id="competition" name="공모전" class="round-button" onclick="updateHiddenValue(this)" value="공모전">
        <input type="hidden" id="selectedCategory" name="selectedCategory" value="{{ notice.category }}">      
        <div id="writingZone">
            <textarea id="titleWriting" name="notion_title" rows="4" cols="50" >{{ notice.notion_title }} </textarea>
            <textarea id="contentsWriting" name="notion_text" rows="10" cols="50" >{{ notice.notion_text }}</textarea>
            <label for="profile" class="round-button" id="addPhotoLabel">
                <span>사진추가</span>
            </label>
            <input type="file" id="profile" name="image" accept="image/png, image/jpeg"  multiple style="display: none;">
            <div class="ifimg" id="imagePreview">    
                <img class="img_icon" src="{% static 'img/Vector.png' %}" id="selectedImageIcon" alt="Img Icon">
                <input class="selectedImageName" id="file" value="" placeholder="선택된 사진이 없습니다." readonly>
            </div>
            <label for="profile2" class="round-button" id="addFileLabel">
                <span>파일추가</span>
            </label>
            <input type="file" id="profile2" name="file" multiple style="display: none;">
            <div class="iffile" id="filePreview" >    
                <img class="img_icon" src="{% static 'img/Vector.png' %}" id="selectedFileIcon" alt="Img Icon">
                <input class="selectedFileName" id="file2" value="" placeholder="선택된 파일이 없습니다." readonly>
            </div>
        </div>
        <input type="submit" id="signUp" value="등록하기">
    </form>
    </div>

    <script src="{% static 'js/Notice_manager_writing.js' %}"></script>
    {% endblock %}

notice/templates/Notice_manager_record.html
{% extends 'basic.html' %}
{% load static %}

    {% block content %}
    <!DOCTYPE html>
    <html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Notice_manager_record.css' %}">
    </head>
    <body>
    <a  href="{% url 'notice:notice_list' %}"><div id="notices" class="notice"><span>공지사항</span></div>
        {% if user.is_superuser %}
        <a href="{% url 'notice:notice_create' %}"><div id="writings" class="writing">글 작성</div></a>
        {% endif %}
<div id="realContent">
    <div id="Notice_title">
        <img id="star" src="{% static 'img/people/star.png'%}" >
        <h1 id="title">Notice</h1>
    </div>
    <form action="{% url 'notice:edit_notice' notion_id=notice.id %}" method="GET">
        {% csrf_token %}
        <div id="regularActivity" class="round-button" name="regularActivity">정기활동</div>
        <div id="event" class="round-button" name="event" >행사</div>
        <div id="competition" class="round-button" name="competition">공모전</div>
        <input type="hidden" id="selectedCategory" name="selectedCategory" value="{{ notice.category }}">
        <!---->
                <span class="category">{{ notice.category }}</span>
         <!--1/24 모바일버전 카테고리 표시때문에 불러옴-->
        <div id="writingZone">
            <textarea id="titleWriting" name="notion_title" rows="4" cols="50" readonly>{{ notice.notion_title }}</textarea>
            <li id="firstLine"></li>
            <li id="secondLine"></li>
            <!---->
            <div id="contentsWriting" name="message2">
                <textarea name="notion_text" readonly>{{ notice.notion_text }}</textarea>
                {% if images %}
                    <div id="imageContainer"> <!-- 부모 요소 추가했음용가리 -->
                        <ul>
                            {% for image in images %}
                                <li><img src="{{ image.image.url }}" alt="Image" width="5%"></li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% if files %}
                <div id="fileContainer"> <!-- 부모 요소 추가했음용가리 -->
                    <ul>
                        {% for file in files %}
                        
                            <li><img id="file_star" src="{% static 'img/Vector.png'%}" ><a href="{{ file.file.url }}" download>{{ file.file.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
           {% endif %}
            </div>
            <!---->
        </div>
        {% if user.is_superuser %}
        <input type="submit" id="editButton" value="수정하기">
        {% endif %}
        <di id="datePart">
            <div id="date">작성일</div>
            <p id="realDate" >{{ notice.write_time }}</p>
        </div>
        
    </form>
</div>
</body>

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="{% static 'js/Notice_manager_record.js' %}"></script>
    {% endblock %}

notice/templates/Notice_manager_writing.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/Notice_manager_writing.css' %}">
<div id="realContent">
<form action="{% url 'notice:notice_create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <a href="{% url 'notice:notice_list' %}"><div id="notices" class="notice"><span>공지사항</span></div></a>
    <div id="writings" class="writing"><span>글 작성</span></div>
    <input type="button" id="regularActivity" name="정기활동" class="round-button" onclick="updateHiddenValue(this)" value="정기활동">
    <input type="button" id="event" name="행사" class="round-button" onclick="updateHiddenValue(this)" value="행사">
    <input type="button" id="competition" name="공모전" class="round-button" onclick="updateHiddenValue(this)" value="공모전">
    <input type="hidden" id="selectedCategory" name="selectedCategory" value="">        
    <div id="writingZone">
        <textarea id="titleWriting" name="notion_title" rows="4" cols="50" placeholder="제목을 입력해주세요"></textarea>
        <textarea id="contentsWriting" name="notion_text" rows="10" cols="50" placeholder="내용을 입력해주세요"></textarea>
        <label for="profile" class="round-button" id="addPhotoLabel">
            <span>사진추가</span>
        </label>
        <input type="file" id="profile" name="image" accept="image/png, image/jpeg" multiple style="display: none;">
        <div class="ifimg" id="imagePreview">    
            <img class="img_icon" src="{% static 'img/Vector.png' %}" id="selectedImageIcon" alt="Img Icon">
            <input class="selectedImageName" id="file" value="" placeholder="선택된 사진이 없습니다." readonly>
        </div>
        <label for="profile2" class="round-button" id="addFileLabel">
            <span>파일추가</span>
        </label>
        <input type="file" id="profile2" name="file" multiple style="display: none;">
        <div class="iffile" id="filePreview" >    
            <img class="img_icon" src="{% static 'img/Vector.png' %}" id="selectedFileIcon" alt="Img Icon">
            <input class="selectedFileName" id="file2" value="" placeholder="선택된 파일이 없습니다." readonly>
        </div>
    </div>
    <input type="submit" id="signUp" value="등록하기">
</form>
</div>
    
<script src="{% static 'js/Notice_manager_writing.js' %}"></script>
{% endblock %}