homepage/urls.py
from django.contrib import admin
from django.urls import path, include
from joinInfo.views import apply_club_user_info_view
from activity.views import upload_activity, success_page, edit_page, edit_images, activities_page
from people.views import show_people_1, show_people_2, show_people_3
from joinResult import views
from application import views
from makers.views import show_makers
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('join/', apply_club_user_info_view, name='apply_club_user_info_view'),
    path('joinResult/', include('joinResult.urls')),

    path('', include('login.urls')),

    path('upload/', upload_activity, name='upload_activity'),
    path('success/', success_page, name='success_page'),
    path('edit/', edit_page, name='edit_page'),
    path('edit_images/<int:image_id>/', edit_images, name='edit_images'),
    path('activities/', activities_page, name='activities_page'),

    path('people_1/', show_people_1, name='show_people_1'),
    path('people_2/', show_people_2, name='show_people_2'),
    path('people_3/', show_people_3, name='show_people_3'),

    path('notice/', include('notice.urls')),  

    path('application/', include('application.urls')),

    path('makers/', show_makers, name='show_makers'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

joinResult/urls.py
from django.urls import path
from . import views
app_name='joinResult'

urlpatterns = [
    path('join_button/',views.join_button, name='join_button'),
    path('send_mail/', views.send_mail, name='send_mail'),
    path('write_form/',views.write_form, name='write_form'),
    path('result/', views.result,name='result'),
    path('writeMail/', views.writeMail, name='writeMail'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('', views.home, name='home'),
    path('h/', views.health, name='health'),
]

notice/urls.py
from django.contrib import admin
from django.urls import path, include
#for images, files
from django.conf.urls.static import static
from django.conf import settings
from notice import views

app_name = 'notice'

urlpatterns = [
    path('', views.notice_list, name='notice_list'),
    path('0/<int:notion_id>/', views.notice_detail, name='notice_detail'),#0이 왜 필요한진 몰겠어요..; 근데 자꾸 주소에 0 붙어서 걍 함
    path('create/', views.notice_create, name='notice_create'),
    path('get_notices_by_category/', views.get_notices_by_category, name='get_notices_by_category'),
    path('edit_notice/<int:notion_id>/', views.edit_notice, name='edit_notice'),
]
#for images, files/ 개발 환경에서 쓸라면 이거 추가해서 직접 서빙해줘야함.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <!--바로아래 메타태그는 css깨지는 mixedContent해결용이랍니다-->
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WAGI WEB PAGE</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/basic_modal.css' %}">
    <link rel="stylesheet" href="http:////spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css">
    <!--js-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{% static 'js/basic_modal.js' %}" data-is-date="{{ isDate }}"></script>



</head>
<body>
    <header id="main-header">
        <a href="{% url 'login:home' %}">
            <img src="{% static 'img/WAGI logo crop.png' %}" alt="logo">
        </a>
        <nav id="main-navigation">
            <ul class="menu">
                <li class="menu-item"><a href="{% url 'activities_page' %}">Activities</a></li>
                <li class="menu-item"><a href="{% url 'show_people_3' %}">People</a></li>
                <li class="menu-item" ><a id="apply" href="{% url 'joinResult:join_button' %}">Join</a></li>
                <li class="menu-item"><a href="{% url 'notice:notice_list' %}">Notice</a></li>
            </ul>
        </nav> 
        <!-- 모바일 전용 -->
        <a>
            <img src="{% static 'img/ci_hamburger-lg.svg' %}" id="category_button" value="">
        </a>

        <div class="slide" id="slide">
            <ul id="slide_menu">
                <li class="menu-item"><a href="{% url 'activities_page' %}">Activities</a></li>
                <li class="menu-item"><a href="{% url 'show_people_3' %}">People</a></li>
                <li class="menu-item" ><a id="apply_" href="{% url 'joinResult:join_button' %}">Join</a></li>
                <li class="menu-item"><a href="{% url 'notice:notice_list' %}">Notice</a></li>
                <li class="menu-item"><a href="{% url 'show_makers' %}">Makers</a></li><!--메이커스 만들고 경로 달아야해여--> 
            </ul>
        </div>
        <!-- 모바일 전용 -->
    </header>
    <!-- 메일 입력창 -->
    <div class="modal_unavailable">
        <div class="modal-box1">
            <img class="imgWagi" src="{% static 'img/WAGI character.png' %}">
            <button id="close-modal">✕</button>
            
            <div class="modal-content1">
                <h2 class="message">지금은 모집 기간이 아니에요!</h2>
                <h4 class="message_2">아래에 메일을 입력해주시면<br>모집 기간에 안내 메일을 발송해드립니다.</h4>
                <form id="email" method="post" action="{% url 'joinResult:writeMail' %}">
                    {% csrf_token %}
                    <div class="email">
                        <input class="input_email" type="email" name="email" placeholder="메일을 입력해주세요." required="required">
                    </div>
                    <div class="out_text">
                        <span>해당 주소로 메일을 보내드리겠습니다.</span>
                    </div>
                </form>
            </div>
            <div class="up">
                <p class="up_message"></p>
            </div>
        </div>
    </div>
    {% block content %}

    {% endblock%}
    <div id="page-wrapper">
        <div id="main-section">
        </div>
    </div> 
    <footer id="main-footer">
        <img src="{% static 'img/WAGI black.png' %}" alt="logo">
        <div class="link">
            <a href="https://www.instagram.com/sswu_wagi?igsh=dTJ1cDFuNWp4Z2pu">
                <img src="{% static 'img/instagram.svg' %}" width="30" height="30">
            </a>

            <a href="https://www.sungshin.ac.kr/ce/index.do">
                <img src="{% static 'img/univ.svg' %}" width="30" height="30">
            </a>

            <a href="https://www.notion.so/WAGI-7ebecf76d8e545d5bc5aceadf5128b3d?pvs=4">
                <img src="{% static 'img/notion.svg' %}" width="30" height="30">
            </a>
        </div>

        <p>ⓒWAGI. 2023 All rights reserved</p>

        <button id="login-button"><a href="{% url 'login:login' %}">LOGIN</a></button>
    </footer>
    <script src="{% static 'js/menu_style.js' %}"></script>
</body>
</html>