application/urls.py
from django.urls import path
from . import views
#for images, files
from django.conf.urls.static import static
from django.conf import settings
app_name='application'

urlpatterns = [
    path('form/', views.applicant_form, name='form'),
    path('join_success/', views.join_success, name='join_success'),
    path('admin_join/', views.admin_join, name='admin_join'),
    path('join_detail/<int:join_id>/', views.join_detail, name='join_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.contrib import admin
from django.urls import path, include
from joinInfo.views import apply_club_user_info_view
from activity.views import upload_activity, success_page, edit_page, edit_images, activities_page
from people.views import show_people_1, show_people_2, show_people_3
from joinResult import views
from application import views
from makers.views import show_makers
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('join/', apply_club_user_info_view, name='apply_club_user_info_view'),
    path('joinResult/', include('joinResult.urls')),

    path('', include('login.urls')),

    path('upload/', upload_activity, name='upload_activity'),
    path('success/', success_page, name='success_page'),
    path('edit/', edit_page, name='edit_page'),
    path('edit_images/<int:image_id>/', edit_images, name='edit_images'),
    path('activities/', activities_page, name='activities_page'),

    path('people_1/', show_people_1, name='show_people_1'),
    path('people_2/', show_people_2, name='show_people_2'),
    path('people_3/', show_people_3, name='show_people_3'),

    path('notice/', include('notice.urls')),  

    path('application/', include('application.urls')),

    path('makers/', show_makers, name='show_makers'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('', views.home, name='home'),
    path('h/', views.health, name='health'),
]

application/models.py
from django.db import models

# Create your models here.

class Application(models.Model):
    introduction = models.CharField(max_length=500)
    motivation = models.CharField(max_length=500)
    project_experience = models.CharField(max_length=800)
    study_experience = models.CharField(max_length=700)
    submit_date = models.DateTimeField(auto_now=True)

application/views.py
from datetime import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django import forms
from django.core.paginator import Paginator
from .models import Application
from joinInfo.models import JoinInfo
from django.contrib.auth.decorators import login_required

# Create your views here.

# forms.ModelForm을 상속받아 지원자 정보를 입력받는 폼을 정의
class ApplicantInfo(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['introduction', 'motivation', 'project_experience', 'study_experience']

        widgets = {'introduction': forms.Textarea(attrs={'class':'inputmodel', 'placeholder':'내용을 입력하세요'}),
            'motivation': forms.Textarea(attrs={'class':'inputmodel', 'placeholder': '내용을 입력하세요'}),
            'project_experience': forms.Textarea(attrs={'class':'inputmodel', 'placeholder':'내용을 입력하세요'}),
            'study_experience': forms.Textarea(attrs={'class':'inputmodel', 'placeholder': '내용을 입력하세요'})
            }

# 지원자 정보를 입력받는 뷰 함수
def applicant_form(request):
    if request.method == 'POST':
        form = ApplicantInfo(request.POST)
        # 폼이 유효한 경우 데이터를 저장하고 페이지 이동
        if form.is_valid():
            app_sub = form.save()
            name = ''
            try:
                obj = JoinInfo.objects.get(pk=app_sub.pk)
                name = obj.user_name
            except JoinInfo.DoesNotExist:
                raise Http404('An error occurred. Please try again.')
            
            # join_success.html로 이동, user_name 전달
            return render(request, 'application/join_success.html', {'name': name})
    else:
        form = ApplicantInfo()

    return render(request, 'application/form.html', {'form': form})

# 지원 성공 페이지를 렌더링하는 뷰 함수
def join_success(request):
    return render(request, 'application/join_success.html')

#각 지원자 정보
@login_required(login_url='/login/')
def admin_join(request):
    page = request.GET.get('page', '1')  # 페이징 기능 추가
    join_list = JoinInfo.objects.order_by('id')
    paginator = Paginator(join_list, 6)  # 페이지당 6개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'join_list':page_obj}
    return render(request, 'application/admin_join.html', context)


#각 지원자당 상세페이지
@login_required(login_url='/login/')
def join_detail(request, join_id):
    join_info = get_object_or_404(JoinInfo, pk=join_id)
    application_info = get_object_or_404(Application, pk=join_id)
    combined_context = {'application_info': application_info, 'join_info': join_info}
    return render(request, 'application/join_detail.html', combined_context)

application/templates/application/admin_join.html
{% extends 'basic.html' %}
{% load static %}
{% block content %}
    <!--css-->
    <link rel="stylesheet" href="{% static 'css/admin_join.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css"/>

    <div id="page-wrapper">
        <div id="content">
           <div class="background">
                <div class="DList">
                    <table class="tbl">
                        <colgroup>
                            <col width="*" />
                            <col width="*" />
                            <col width="*" />
                            <col width="*" />
                            <col width="43%" />
                        </colgroup>
                        <thead>
                            <th>번호</th>
                            <th>학번</th>
                            <th>이름</th>
                            <th>학과</th>
                            <th>지원서</th>
                        </thead>
                        <!-- 데이터 불러온 부분 -->
                        <tbody>
                            {% if join_list %}
                            {% for join_objects in join_list %}
                            <tr onclick=location.href="{% url 'application:join_detail' join_objects.id %}">
                                <td>{{ join_objects.id }}</td>
                                <td>{{ join_objects.user_number }}</td>
                                <td>
                                    {{ join_objects.user_name }}
                                </td>
                                <td>{{ join_objects.user_major }}</td>
                                <td>지원서 제출 완료</td>
                            </tr>
                            {% endfor %}
                            {% endif %}
                            </tbody>
                    </table>
                </div>
                <div class="paging">
                    <!-- 이전페이지 -->
                    {% if join_list.has_previous %}
                    <a class="link" href="?page={{ join_list.previous_page_number }}">
                        <i class="fa-solid fa-angle-left" id="prev_page"></i>
                    </a>
                    {% else %}
                    <a class="link" tabindex="-1" aria-disabled="true" href="#">
                        <i class="fa-solid fa-angle-left" id="prev_page"></i>
                    </a>
                    {% endif %}
                    <!-- 페이지리스트 -->
                    <div class="pages">
                    {% for page_number in join_list.paginator.page_range %}
                    {% if page_number >= join_list.number|add:-5 and page_number <= join_list.number|add:5 %}
                    {% if page_number == join_list.number %}
                    <span class="active" aria-current="page">
                        <a class="link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </span>
                    {% else %}
                    <span>
                            <a class="link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </span>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    </div>
                    <!-- 다음페이지 -->
                    {% if join_list.has_next %}
                    <a class="link" href="?page={{ join_list.next_page_number }}">
                        <i class="fa-solid fa-angle-right" id="next_page"></i>
                    </a>
                    {% else %}
                    <a class="link" tabindex="-1" aria-disabled="true" href="#">
                        <i class="fa-solid fa-angle-right" id="next_page"></i>
                    </a>
                    {% endif %}
                </div>
                <!-- 페이징처리 끝 -->
           </div>
        </div>     
    </div> 
{% endblock %}

application/templates/application/form.html
{% extends 'basic.html' %}
{% load static %}
{% block content %}

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">

    <div class="page-wrapper1">
        <div class="join-title">
            <img class="star" src="{% static 'img/people/star.png' %}">
            <h1 class="title1">join</h1>
        </div>
        <div class="main-section1">
            <form method="post" action="{% url 'application:form' %}">
                {% csrf_token %}
        
                <div class="container">
                    <div class="question-box">
                        <p style="margin: 0;">1. 자기소개를 해주세요. (500자 내외)</p>
                    </div>
                    <div class="answer-box">
                        {{ form.introduction|default_if_none:'' }}
                    </div>
                
                    <div class="question-box">
                        <p style="margin: 0;">2. 지원동기를 작성해주세요. (500자 내외)</p>
                    </div>
                    <div class="answer-box">
                        {{ form.motivation|default_if_none:'' }}
                    </div>
                
                    <div class="question-box">
                        <p style="margin: 0;">3. 프로젝트 관련 경험이 있다면 작성해주세요. (800자 내외)</p>
                    </div>
                    <div class="answer-box">
                        {{ form.project_experience|default_if_none:'' }}
                    </div>
                
                    <div class="question-box">
                        <p style="margin: 0;">4. 개발과 관련한 공부를 한 경험이 있다면 작성해주세요. (700자 내외)</p>
                    </div>
                    <div class="answer-box">
                        {{ form.study_experience|default_if_none:'' }}
                    </div>
                
                </div>
        
                <div class="container2">
                    <a href="{% url 'application:join_success' %}">
                        <button type="submit" class="submit-button">지원서 제출</button>
                    </a>
                </div>
            </form>
        
        </div>
    </div>
{% endblock %}

application/templates/application/join_detail.html
{% extends 'basic.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>지원서</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/join_detail.css' %}">
</head>

<body>

    <div class="container" >
        {% if application_info %}
        <div class="container1">
            <div class="box1" >번호</div><div class="joininfo">{{join_info.id}}</div>
            <div class="box2" >학과</div><div class="joininfo">{{join_info.user_major}}</div>
            <div class="box3" >제출일시</div><div class="joininfo">{{application_info.submit_date}}</div>
            <br>
            <div class="box4" >이름</div><div class="joininfo">{{join_info.user_name}}</div>
            <div class="box5" >학번</div><div class="joininfo">{{join_info.user_number}}</div>
        </div>

    <!-- 데이터 불러온 부분 -->

    
        <div class="question-box " >
            <p  style="margin: 0">1. 자기소개를 해주세요. (500자 내외)</p>
        </div>
        <div class="answer-box" >
            {{ application_info.introduction }}
        </div>

        <div class="question-box">
            <p style="margin: 0;">2. 지원동기를 작성해주세요. (500자 내외)</p>
        </div>
        <div class="answer-box" >
            {{ application_info.motivation }}
        </div>
    
        <div class="question-box">
            <p style="margin: 0;">3. 프로젝트 관련 경험이 있다면 작성해주세요. (800자 내외)</p>
        </div>
        <div class="answer-box">
            {{ application_info.project_experience }}
        </div>
    
        <div class="question-box" >
            <p style="margin: 0;">4. 개발과 관련한 공부를 한 경험이 있다면 작성해주세요. (700자 내외)</p>
        </div>
        <div class="answer-box">
            {{ application_info.study_experience }}
        </div>

        {% else %}
        상세페이지가 없습니다.
        {% endif %}

    </div>
</body>
</html>
{% endblock %}

application/templates/application/join_success.html
{% extends 'basic.html' %}
{% load static %}
{% block content %}
    <!--css-->
    <link rel="stylesheet" href="{% static 'css/join_success.css' %}" />
    <link rel="stylesheet" href="https:////spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css">

    <div id="page-wrapper">
        <div class="join-title">
            <img class="star" src="{% static 'img/people/star.png' %}">
            <h1 class="title1">join</h1>
        </div>
        <div id="content">
            <div class="modal-box">
                <img class="imgWagi" src="{% static 'img/WAGI character.png' %}">
                <div id="underline"></div>
                <div class="modal-content">
                    <h2 class="message">{{name}}님!</h2>
                    <h2 class="message">지원이 완료되었습니다.<br>1차 합격자 조회 기간은<br>3월 9일 18:00 - 3월 10일 18:00 입니다. </h2>
                </div>
            </div>
        </div>
    </div>
{% endblock %}