homepage/urls.py
from django.contrib import admin
from django.urls import path, include
from joinInfo.views import apply_club_user_info_view
from activity.views import upload_activity, success_page, edit_page, edit_images, activities_page
from people.views import show_people_1, show_people_2, show_people_3
from joinResult import views
from application import views
from makers.views import show_makers
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('join/', apply_club_user_info_view, name='apply_club_user_info_view'),
    path('joinResult/', include('joinResult.urls')),

    path('', include('login.urls')),

    path('upload/', upload_activity, name='upload_activity'),
    path('success/', success_page, name='success_page'),
    path('edit/', edit_page, name='edit_page'),
    path('edit_images/<int:image_id>/', edit_images, name='edit_images'),
    path('activities/', activities_page, name='activities_page'),

    path('people_1/', show_people_1, name='show_people_1'),
    path('people_2/', show_people_2, name='show_people_2'),
    path('people_3/', show_people_3, name='show_people_3'),

    path('notice/', include('notice.urls')),  

    path('application/', include('application.urls')),

    path('makers/', show_makers, name='show_makers'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('', views.home, name='home'),
    path('h/', views.health, name='health'),
]

joinInfo/models.py
from django.db import models

class JoinInfo(models.Model):
    user_name = models.CharField(max_length=15)
    user_number = models.IntegerField()
    user_major = models.CharField(max_length=30)
    user_phone_number = models.IntegerField()
    user_file=models.FileField(upload_to="applications/", null=True, blank=False)

# Create your models here.

joinInfo/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django import forms
from .models import JoinInfo
from django.http import Http404
from django.contrib import messages

# Create your views here.

class ApplicantForm(forms.ModelForm):
    class Meta:
        model = JoinInfo
        fields = ['user_name', 'user_number', 'user_major', 'user_phone_number', 'user_file']

def apply_club_user_info_view(request):
    if request.method == 'POST':
        form = ApplicantForm(request.POST, request.FILES)
        idcheck=request.POST.get('user_number')
        #기존에 한번 지원한 친구들은 빠꾸맥이기~ 어쩔수 엇ㅂ어 안하면 오류나; 정신똑바로차리고살아야지이런각박한세상속에서
        if JoinInfo.objects.filter(user_number=idcheck).exists():
            error_message = '이미 지원 완료된 학번입니다.<br>관련 문의는 인스타그램 @sswu_wagi로 부탁드립니다.'
            messages.error(request, error_message, extra_tags='safe')
            return render(request, 'join_info.html', {'form': form})
        
        if form.is_valid():
            app_sub=form.save()
            name = ''
            try:
                obj = JoinInfo.objects.get(pk=app_sub.pk)
                name = obj.user_name
            except JoinInfo.DoesNotExist:
                raise Http404('An error occurred. Please try again.')
            
            # join_success.html로 이동, user_name 전달
            return render(request, 'application/join_success.html', {'name': name})
    else:
        form = ApplicantForm()

    return render(request, 'join_info.html', {'form': form})

joinInfo/templates/join_info.html
{% extends 'basic.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/joinBasicInfo.css' %}">
    <script src="{% static 'js/joinBasicInfo.js' %}"></script>

    <div id="page-wrapper1">
        <div class="join-title">
            <img class="star" src="{% static 'img/people/star.png' %}">
            <h1 class="title1">join</h1>
        </div>
        <div class="content">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}
                style="color: rgb(204, 45, 45); font-size: larger;">{{ message|safe }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        <div id="main-section1">
            <div class="info-box" style="background-color: #9EA9D7;">
                <div class="info-text">
                    지원서 작성
                </div>
            </div>
            <div id="form_box">
            <form method="post" action="{% url 'apply_club_user_info_view' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="input-box">
                
                    <div class="input-container">
                        <!-- 이름 입력 -->
                        <label for="name" style="color: #999898;">이름</label>
                        {{ form.user_name }}
                        <div class="warning-message" id="warningName">{{ form.user_name.errors }}</div>

                        <!-- 학번 입력 -->
                        <label for="studentID" style="color: #999898;">학번(수험번호)</label>
                        <input type="number" name="{{ form.user_number.name }}" placeholder="신입생은 무조건 '수험번호'로 입력 바랍니다" id="{{ form.user_number.id_for_label }}" class="input-n">
                        <div class="warning-message" id="warningStudentID">{{ form.user_number.errors }}</div>

                        <!-- 학과 입력 -->
                        <label for="id_user_major" style="color: #999898;" class="input-label">학과</label>
                        {{ form.user_major }}
                        <div class="warning-message" id="warningDepartment">{{ form.user_major.errors }}</div>

                        <!-- 전화번호 입력 -->
                        <label for="id_user_phone_number" style="color: #999898;" class="input-label">전화번호('-'없이 입력해 주세요)</label>
                        {{ form.user_phone_number }}
                        <div class="warning-message" id="warningPhoneNumber">{{ form.user_phone_number.errors }}</div>
                        <!--지원서 업로드-->
                        <label for="id_user_file" class="input-label" id="addFileLabel" style="color: #999898;">지원서 업로드</label>
                        {{ form.user_file }}
                        <div class="warning-message" id="warningFile">{{ form.user_file.errors }}</div>
                        <div class="iffile" id="filePreview" >
                            <input class="selectedFileName" id="file2" value="" placeholder="선택된 파일이 없습니다." readonly>
                        </div>
                    </div>
                </div>
                <!-- 지원서 작성하기 버튼 -->
                <button type="submit" class="enter" id="enter-button">지원서 제출하기</button>
            </form>
        </div>
        </div>
    </div>
    </div>
    <script src="{% static 'js/joinBasicInfo.js' %}"></script>
{% endblock %}